apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
  - host: devbootcamp-rest-graph.id
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: twittorapi-clusterip-srv
            port: 
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kafkaapp-clusterip-srv
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kafkalistening-clusterip-srv
            port:
              number: 80
