# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  twittorapi:
    image: renosatyaadrian/twittorapi
    build:
      context: .
      dockerfile: TwittorAPI/Dockerfile
    ports:
      - 5002:5002
  kafkalisteningappapi:
    image: renosatyaadrian/kafkalisteningservice
    build:
      context: .
      dockerfile: KafkaListeningApp/Dockerfile
    ports:
      - 7001:7001
  kafkaappapi:
    image: renosatyaadrian/kafkaappservice
    build:
      context: .
      dockerfile: KafkaApp/Dockerfile
    ports:
      - 6001:6001
#   zookeeper:
#     image: docker.io/bitnami/zookeeper:latest
#     ports:
#       - "2181:2181"
#     volumes:
#       - "./zookeeper_data:/bitnami"
#     environment:
#       - ALLOW_ANONYMOUS_LOGIN=yes
#   kafka:
#     image: docker.io/bitnami/kafka:latest
#     ports:
#       - "9093:9093"
#       - "29092:29092"
#     volumes:
#       - "./kafka_data:/bitnami"
#     environment:
#       # - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#       # - ALLOW_PLAINTEXT_LISTENER=yes
#       # - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
#       # - KAFKA_CFG_LISTENERS=CLIENT://:9093,EXTERNAL://:9092
#       # - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9093,EXTERNAL://kafka:9092
#       # - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      
#       - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#       - ALLOW_PLAINTEXT_LISTENER=yes
#       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
#       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#     depends_on:
#       - zookeeper

# volumes:
#   zookeeper_data:
#     driver: local
#   kafka_data:
#     driver: local

  
